CREATE DATABASE IF NOT EXISTS sahabat_umkm_ai
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE sahabat_umkm_ai;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  business_name VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
